name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: checkout do repositorio
      uses: actions/checkout@v4.1.1
   
    - name: Efetuar o login no docker hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PWD}} 
      
    - name: Envia a imagem para o docker registry
      uses: docker/build-push-action@v5.0.0
      with:
        context: ./kube-news/src
        file: ./kube-news/src/Dockerfile
        push: true
        tags: |
          hernanisoares/kube-news:${{ github.run_number }}
          hernanisoares/kube-news:latest
      
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - name: checkout do repositorio
      uses: actions/checkout@v4.1.1

    - name: "Configure AWS Credentials" 
      uses: aws-actions/configure-aws-credentials@v4
      with:
        # AWS Region, e.g. us-east-2
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
      
    - name: Configurar o kubeconfig
      run: aws eks update-kubeconfig --name eks-imersao --region us-east-1
      
    - name: Aplicar o deploy
      uses: Azure/k8s-deploy@v4.9
      with:
        manifests: |
          ./kube-news/k8s/deployment.yml
        images: |
          hernanisoares/kube-news:${{ github.run_number }}
        
      
